Задание 1-2
Divium-l/ProcedureProgramming-Rodionov pull request #5
Opened 2021-03-05 18:49 UTC by Divium-l

1. Написана программа
2. Создана блок-схема алгоритма

2021-03-05 22:13 UTC, MarinaPaley requested changes
Хочу похвалить за решение. Но, там есть над чем поработать!

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +				if ((str[i] == '.' && isFloat)) isValid = false;
кажется, что это условие никогда не будет выполняться, недостижимый код

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +		for (int i = 0; i < str.length(); i++)
я бы лучше использовала цикл `while  (i < str.length() && isValid)) {}`

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +
`#include <cmath>` ?

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +		cin >> str;
Почему-то Вы забыли пользователя попросить ввести число

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +	double a = input();
я рада, что есть этот метод. 
задачи были написаны для `C#` и потом не отредактированы. В `C#` проверку осуществлять намнго проще.  Я пока всем не планирую давать задание с проверкой. Подумайте, этот метод можно и нужно изменить.. 
По задаче в целом. 
По всей програме хороший `naming`, но не при выборе `a` - `legth`?

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +	cout << "Face area = " << pow(a, 2) << endl;
вынесите все расчеты в отдельные функции, раз Вы это умеете.
лучше  в первых двух строках использовать `\n`, чтобы не прерывать поток исполнения
формула будет лучше читаться с пробелами `6 * pow(a,2)`
использование функций даст возможность при расчете полной площади использовать уже посчитанную площадь грани

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +				if ((str[i] == '.' && !isFloat)) isFloat = true;
строку можно переписать `isFloat = str[i] == '.' ;`

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +		else break;
старайтесь избегать `break`. Трудно понимать программу
старайтесь писать с правильными отсутпами, не экономя на форматировании

2021-03-05 22:13 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +		if (str[0] == '-')
Я бы все-таки проверила, что у строки есть длина, и она больше нуля. Ну, уж после того, как "откусили" минус - точно проверять нужно - падает с грохотом(

2021-03-07 19:19 UTC, Divium-l commented on task-1-2/task-1-2.cpp
> +	double a = input();
Не понял по поводу метода. Нужно как-то поменять функцию input()?

2021-03-12 22:35 UTC, MarinaPaley requested changes
Добавьте `const`, все остальное хорошо

2021-03-12 22:35 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +double calcFaceArea(double length)
`(const double length)`

2021-03-12 22:35 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +double calcSurfaceArea(double length)
`(const double length)`

2021-03-12 22:35 UTC, MarinaPaley commented on task-1-2/task-1-2.cpp
> +double calcVolume(double length)
`(const double length)`

2021-03-15 19:44 UTC, MarinaPaley approved these changes
Метод `input` имеет две разные ответственности: ввод пользовательский данных и `parse`. Так делать плохо, т.к. меод полцчается длинный и сложно воспринимаемый. Когда придет время, я всех группе буду объяснять как лучше делать "защиту дурака".

2021-03-16 06:16 UTC, merged